### ISSUE TITLE
Web UI?

### ISSUE THREAD

**Issue by maxehmookau** [substrakt/letsencrypt-heroku#11]
Could investigate the idea of wrapping the API in some sort of JS application for those less keen on using an API directly.

**Comment by StanBoyet** [comment]
Hi @maxehmookau , 

I thought it was a good idea, though I didn't think it should be the same app as this one as it doesn't serve the same purpose.

This is why we made [a UI/dashboard](https://github.com/Drawbotics/letsencrypt-heroku-dashboard) at Drawbotics.

The purpose is to give a proper UI (for now) and to track the previous requests (which was missing from the API in my opinion, as I was using it).

The next step is to have the `auto-renew` in place, as I feel it doesn't belong in `letsencrypt-heroku`. The way I see it is that `letsencrypt-heroku` is "just" a hub between Let's Encrypt, Heroku & Cloudflare. Not the app to manage the business, which the dashboard should do.

Anyway. We went ahead to build something useful for us (we use it in production since... 2 hours ago 😁  ) on top of your awesome software (which was really useful, thanks a lot). If you have any remarks, tips or else, feel free to reach out ! 

Cheers

**Comment by maxehmookau** [comment]
HI @StanBoyet.

Firstly, sorry for my slow reply, I've been on holiday.

Secondly:
*WOW!* +💯 

This is excellent! Thanks for all your hard work, lovely to see this project taking off!

I've been thinking about this a lot recently and you're right, auto-renew doesn't belong in this library I don't think. This API should be simply a link between LE/Heroku & CloudFlare as you correctly suggest. So projects like yours are the next logical step. That said, in the future I'd like to include a very lightweight UI with the project but nothing as full-featured as yours.

You should be aware, however, that I'm half way through rewriting the API to be more RESTful (no more GET requests for _everything!_) You can see how it's going here: https://github.com/substrakt/letsencrypt-heroku/tree/2.0-rewrite

**Comment by StanBoyet** [comment]
Hey max,

Once you have an API doc for the next release, I'll be happy to update our app to match it !
I'll stop working on this during "office" hours though, and switch to our classic Thursday side projects afternoon 😁  I think I'll start the auto-renew. 

I'm happy to see "no more GET requests for everything!" by the way, it's only gonna make my life easier 😉 

I'll follow closely the 2.0 rewrite then !

Cheers

**Comment by maxehmookau** [comment]
Great, I'll keep you posted when the 2.0 release happens! I'll also look at maybe sending a few PRs your way. I noticed there's quite a lot of logic in your controllers so I'd love to help with tidying that up a little.
Thanks again for your work!

**Comment by StanBoyet** [comment]
Oh yeah there is, it really is a first draft and needs tidying a bit. I’d love to delegate all the work to services, as we do for our company projects.

My pleasure ;-)
