### ISSUE TITLE
Root domain

### ISSUE THREAD

**Issue by polkovnikov-ph** [substrakt/letsencrypt-heroku#20]
What should I specify in `subdomains` query parameter, if the domain I'd like to get a certificate for is `domain.tld`, without any `www.` etc.?

**Comment by samknight** [comment]
I believe root domain is done whether or not a subdomain is stated

**Comment by polkovnikov-ph** [comment]
@samknight  Well, guessing is a bad thing when it comes to security. I didn't guess, took a proper `certbot` distro and got SSL running via manual process. It seems

> This is alpha software.

message is not the result of authors being humble.

**Comment by samknight** [comment]
Root domains worked for me when I got this working last night hence why I couldn't confirm at that moment.

Feel free to create a pull request if you want to help make this more stable for your needs.

**Comment by maxehmookau** [comment]
Indeed, the warning about this being alpha was a clear statement and nothing to do with humility I'm afraid!

By default, root domains are always covered. Subdomains are optional.

**Comment by polkovnikov-ph** [comment]
@maxehmookau Just add some code that defaults `subdomains` to an empty list if it's absent in the query, please. It will make the process a little bit more obvious.

**Comment by maxehmookau** [comment]
It's on our list to do but we have lots of other projects that we work on currently both public and private. 
If it's an urgent concern then feel free to submit a pull request with the change otherwise it'll happen when our schedule allows. Generally speaking we work on our OSS projects on a Tuesday.
Thank you for bringing it to our attention.
