### ISSUE TITLE
Remove unneccessary environment variables from app.json

### ISSUE THREAD

**Issue by richardrl** [substrakt/letsencrypt-heroku#37]
I've tried inputting both the "ID" and "Token" generated by the oauth command but they don't work.
Creating OAuth Authorization... done
Client:      <none>
ID:          [my id]
Description: letsencrypt-heroku
Scope:       global
Token:       [my token]

https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Fsubstrakt%2Fletsencrypt-heroku&template=https%3A%2F%2Fgithub.com%2Fsubstrakt%2Fletsencrypt-heroku%2Ftree%2Fmaster

They don't work with the above link

**Comment by maxehmookau** [comment]
Ah, this is a bug. In the latest version, the heroku oauth token is defined in the actual API call, not in the environment variable which is why it won't be working.

Make sure your API call looks like the example in the README (https://github.com/substrakt/letsencrypt-heroku#usage) and leave the environment variable blank as it'll have no effect.

I'll try to resolve this after the holidays. Thanks for bringing it to my attention though! 👍
